### PR TITLE
[DevOps Center] Merge WI-000002 to Staging

### PR DESCRIPTION
**Pull request by Hd19781978**
DevOps Center created this pull request. It will be merged automatically upon promotion in DevOps Center. If you merge it outside of DevOps Center, DevOps Center provides you the option to deploy the changes to complete the promotion.

### CODE REVIEW

**Comment by buffaloupsalesforce** [comment]
Handan Hanim flow un screenshot ini koyabilirmisiniz

**Comment by myarchivex6** [comment]
Bu flow tam olarak ne yapiyor

**Review by myarchivex6 — COMMENTED** [review]
Handan hanim flow screenshot eklermisiniz

**Comment by Hd19781978** [comment]
> Handan hanim flow screenshot eklermisiniz



> Handan hanim flow screenshot eklermisiniz

ekledim cek edebilirsiniz

**Review by myarchivex6 — APPROVED** [review]
Approved Thanks

**Pull request merged**
